server:
  port: 8082
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bdcontroleest
    password: 1010
    username: postgres
    driverClassName: org.postgresql.Driver
